# Generated by Django 2.1.5 on 2019-02-21 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humorge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecomment',
            name='freeboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_comments', to='humorge.FreeBoard'),
        ),
        migrations.AlterField(
            model_name='humorcomment',
            name='humorboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humor_comments', to='humorge.HumorBoard'),
        ),
    ]
